# Generated by Django 4.0.8 on 2022-11-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('definition', models.TextField()),
                ('variations', models.TextField(default='')),
                ('pronounciation', models.FileField(upload_to='uploads/audios')),
                ('phrases', models.TextField(default='')),
                ('examples', models.TextField(default='')),
                ('approved_status', models.BooleanField(default=True)),
            ],
        ),
    ]
