# Generated by Django 4.0.8 on 2022-11-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='phrases',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronounciation',
            field=models.FileField(blank=True, upload_to='uploads/audios'),
        ),
        migrations.AlterField(
            model_name='word',
            name='variations',
            field=models.TextField(blank=True, default=''),
        ),
    ]
