# Generated by Django 4.0.8 on 2022-12-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_alter_word_phrases_alter_word_pronounciation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
