# Generated by Django 4.0.8 on 2022-12-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_word_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('published_date', models.DateField(blank=True)),
                ('approved_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/images'),
        ),
    ]
