# Generated by Django 4.0.8 on 2022-12-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_comment_word_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
